---
- name: Initialize kubeadm on seed node ... it can take a while.
  shell: |
    curl -sfL https://goyaki.clastix.io | bash -s init
  become: true
  environment:
    DEBUG: "false"
    KUBERNETES_VERSION: "{{ kubernetes_version }}"
    CONTAINERD_VERSION: "{{ containerd_version }}"
    RUNC_VERSION: "{{ runc_version }}"
    CNI_VERSION: "{{ cni_version }}"
    CRICTL_VERSION: "{{ crictl_version }}"
    KUBEADM_CONFIG: /etc/kubernetes/kubeadm-config.yaml
  when: seed is defined and seed | bool
  register: init_output

# - name: Debug init command output
#   debug:
#     var: init_output.stdout
#   when: seed is defined and seed | bool

