
---
- name: Prepare the kubeadm-config file
  become: true
  block:
  - name: Ensure /etc/kubernetes directory exists
    file:
      path: /etc/kubernetes
      state: directory
      mode: '0755'

  - name: Set control plane effective port
    set_fact:
      control_plane_endpoint_port: "{{ control_plane_lb_port if control_plane_lb | default(false) else control_plane_port }}"

  - name: Load kubeadm configuration file from template
    template:
      src: kubeadm-config.yaml.j2
      dest: /etc/kubernetes/kubeadm-config.yaml
      mode: '0644'
  when: seed is defined and seed | bool