---
- name: Setup Control Plane
  hosts: control_plane
  become: true
  become_method: sudo
  become_user: root
  roles:
  - role: keepalived
  - role: haproxy
    when: (control_plane_lb | default(false))
  - role: init
  - role: taint
  - role: cni_plugin






