---
- name: Set seed node to the first control plane node
  hosts: localhost
  tasks:
    - name: Set seed node to the first control plane node
      set_fact:
        seed_node: "{{ groups['control_plane'][0] }}"
      run_once: true

- name: Copy admin.conf from seed node to local machine
  hosts: localhost
  tasks:
    - name: Ensure .kube directory exists
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy admin.conf from seed node to local machine
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        flat: yes
      delegate_to: "{{ seed_node }}"
      become: true