---
- name: Remove Kubernetes cluster from all machines
  shell: |
    curl -sfL https://goyaki.clastix.io | bash -sx -s reset
  become: true
  environment:
    REBOOT: 'false'
    DEBUG: 'false'
  register: reset_output
  ignore_errors: true
