---
- name: Remove Kubernetes cluster from all machines ... it can take a while.
  shell: |
    curl -sfL https://goyaki.clastix.io | bash -sx -s reset
  become: true
  environment:
    REBOOT: 'false'
    DEBUG: 'false'
  register: reset_output
  ignore_errors: true

- name: Stop and disable keepalived service
  become: true
  systemd:
    name: keepalived
    state: stopped
    enabled: no
  ignore_errors: true

- name: Remove keepalived package
  become: true
  apt:
    name: keepalived
    state: absent
  ignore_errors: true

- name: Stop and disable haproxy service
  become: true
  systemd:
    name: haproxy
    state: stopped
    enabled: no
  ignore_errors: true
  when: (control_plane_lb | default(false))

- name: Remove haproxy package
  become: true
  apt:
    name: haproxy
    state: absent
  ignore_errors: true